# Generated by Django 4.1 on 2022-08-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_id', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('land_address', models.CharField(max_length=100)),
                ('detail_address', models.CharField(max_length=30, null=True)),
                ('res_number', models.CharField(max_length=15)),
                ('xpos', models.FloatField()),
                ('ypos', models.FloatField()),
            ],
        ),
    ]
